# addons:
#   apt:
#     packages:
#       ant

# matrix:
#   include:
#   - language: android
#     install: ant deps
#     dist: trusty
#     script:
#   - ./gradlew build --scan -s
#     android:
#         components:
#         # Uncomment the lines below if you want to
#         # use the latest revision of Android SDK Tools
#         # - tools
#         # - platform-tools

#         # The BuildTools version used by your project
#         - build-tools-28.0.3

#         # The SDK version used to compile your project
#         - android-28
#   - language: node_js
#     script:
#       - cd backend && npm test 
matrix:
  include:
  #   sudo: required

  # - language: android
  #   jdk: oraclejdk8

  #   before_cache:
  #     - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  #     - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

  #   cache:
  #     directories:
  #     - $HOME/.gradle/caches/
  #     - $HOME/.gradle/wrapper/
  #     - $HOME/.android/build-cache

  #   env:
  #   global:
  #   - ANDROID_API=28
  #   - ANDROID_BUILD_TOOLS=28.0.3

  #   android:
  #     components:
  #     - tools
  #     # - tools # Running this twice get's the latest build tools (https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI)
  #     - platform-tools
  #     - android-${ANDROID_API}
  #     - build-tools-${ANDROID_BUILD_TOOLS}
  #     - extra

  #    before_script:
  #     - cd Jarvis

  #   script:
  #   - ./gradlew clean test build


    - language: android
      dist: trusty
      jdk: oraclejdk8
      android:
        components:
          - tools
          - android-28
          - build-tools-28.0.3
      before_script:
        - cd Jarvis
      script:
          - ./gradlew clean test build