# addons:
#   apt:
#     packages:
#       ant

# matrix:
#   include:
#   - language: android
#     install: ant deps
#     dist: trusty
#     script:
#   - ./gradlew build --scan -s
#     android:
#         components:
#         # Uncomment the lines below if you want to
#         # use the latest revision of Android SDK Tools
#         # - tools
#         # - platform-tools

#         # The BuildTools version used by your project
#         - build-tools-28.0.3

#         # The SDK version used to compile your project
#         - android-28
#   - language: node_js
#     script:
#       - cd backend && npm test 
matrix:
  include:

    - language: android
      dist: trusty
      jdk: oraclejdk8
      android:
        components:
          - tools
          - android-28
          - build-tools-28.0.3
      before_script:
        - cd Jarvis
      script:
        - ./gradlew build androidTest